services:
  - type: web
    name: linkedin-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: linkedin-scraper-db
          property: connectionString

databases:
  - name: linkedin-scraper-db
    databaseName: linkedin_scraper
    user: linkedin_user